version: '3.8'

services:
  signifly-server:
    build: 
      context: .
      target: dev
    ports:
      - '80:8000'
    volumes:
      - .:/var/www/html:cached
      - ./server/ngnix.conf:/etc/nginx/conf.d/server.conf
    container_name: signifly-server
    depends_on:
      - mysql

  mysql:
    build: 
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: proot
      MYSQL_DATABASE: signifly_teams
    ports:
      - '3306:3306'
    container_name: mysql
  